### PR TITLE
More more datasets

### PR DESCRIPTION
**Pull request by hackalog**
Clean up the COIL-20 dataset, add ORL, HIVA, Shuttle, more dataset infrastructure

### CODE REVIEW

**Comment by acwooding** [comment]
There appears to be datasets.load_dataset('f-mnist') but no datasets.load_fmnist() (or something like that)...

**Comment by acwooding** [comment]
Would be nice to be able to see what datsets are available easily. Made a separate issue (#40) for this.

**Comment by hackalog** [comment]
> There appears to be datasets.load_dataset('f-mnist') but no datasets.load_fmnist() (or something like that)...

Since the data formats are identical, mnist and f-mnist are both loaded by the same function (`load_mnist`), but with different dataset names

That being said, you should load datasets through the `load_dataset(dataset_name)` function, instead of the individual ones. That will (eventually) do all the fetch, cache, etc.

So right now, you can do `load_dataset('f-mnist')` and it should work just fine.

**Comment by acwooding** [comment]
Oh. That seems confusing that load_mnist loads both (that's different behaviour than everything else).

**Comment by hackalog** [comment]
It is, but I decided against duplicating the fetch / cache and return_X_y options in every loader, so I just built the `load_dataset` wrapper to do that, and have it call the individual processing functions itself. That way, the user need not be concerned about what the actual function name/arguments call is.

**Pull request merged**
